### PR TITLE
Parsed body from php input XML/Json

### PR DESCRIPTION
**Pull request by nicholasruunu**
GlobalServerRequest will construct a ServerRequestInterface that will give XML/Json parsed bodies if the content types matches the requirements.
If none of the content types matches, then what was passed to RawParsedBody will be returned (`$_POST`).

I'm not a fan of not being able to typehint the return type of `ParsedBody->parse(contentTypes, stream)` but the interface allows `stdClass`, `array` and `null` to be returned.

### Important changes
[GlobalServerRequest](https://github.com/PuristPHP/http-message/pull/8/files#diff-e93e496b28514a516919da319d953bac)
[MaybeJsonParsedBody](https://github.com/PuristPHP/http-message/pull/8/files#diff-93600c6af325da5e56f1602d24b1bba3)
[MaybeXmlParsedBody](https://github.com/PuristPHP/http-message/pull/8/files#diff-3e6d2663f7ad08561bd83f8c0cf1b582)

### Questions
1. Is it reasonable to run read the `php://input` stream on the ServerRequest to parse the XML/Json (when needed) without replaying?
2. Is it enough to check content types for `application/json`, `application/xml`, `text/xml`?
3. Is there a better way to do this and is XML/Json enough to support by default?
4. Other concerns?

### CODE REVIEW

**Comment by magnusnordlander** [comment]
What about `application/x-www-form-urlencoded` and `multipart/form-data`?

**Comment by magnusnordlander** [comment]
And also, if you're handling e.g. `application/json`, wouldn't it also be a good idea to handle `+json` MIME types? Usually those should be preferable to using a generic MIME type.

**Comment by nicholasruunu** [comment]
Since it's not being picked up by Json nor Xml parsed body, $_POST would be returned on `application/x-www-form-urlencoded` and `multipart/form-data`.

Can you elaborate on the +json mime types?

**Comment by magnusnordlander** [comment]
So, a couple of examples:

 * `application/rss+xml`
 * `application/rdf+xml`
 * `application/ld+json`

Basically it's saying that "This is RSS, which is a kind of XML". This is known as media type suffixes, and hints at the underlying structure of the media type. Cf. [wikipedia](https://en.wikipedia.org/wiki/Media_type#Suffix)

**Comment by nicholasruunu** [comment]
Right, sounds like a good idea, I'll work that in there.

**Comment by nicholasruunu** [comment]
Realised I can't make XML to array/stdClass reliably so it's removed for now.
If you have feedback for XML or other ideas for valid parsed bodies let me know.

**Comment by magnusnordlander** [comment]
You could return a SimpleXMLElement, I suppose.

**Comment by nicholasruunu** [comment]
@magnusnordlander What bothers me is this part of the meta document:
http://www.php-fig.org/psr/psr-7/meta/#why-parsed-body-in-the-serverrequestinterface

```
$data = $request->getParsedBody();
if (! $data instanceof \stdClass) {
    // raise an exception!
}
// otherwise, we have what we expected
```

It seems like the object part of `array|null|object` return doc of the `getParsedBody` implies that it's stdClass. I'm not 100% sure of this though.

**Comment by weierophinney** [comment]
Weighing in as editor of psr-7... Because different formats have different capabilities, we allowed for any type of object to be returned. In particular, with XML, you may need to provide access to both values and attributes, which is not easily modeled as either an array or stdclass object.

**Comment by nicholasruunu** [comment]
Thanks @weierophinney, that helps a lot. `SimpleXMLElement` it is.

**Comment by nicholasruunu** [comment]
Missing media type suffixes checks for `XmlParsedBody`.

**Pull request merged**
